# Generated by Django 5.0.1 on 2024-04-08 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phoneno',
            field=models.IntegerField(),
        ),
    ]
