# Generated by Django 5.0.1 on 2024-04-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_api', '0002_alter_customer_phoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phoneno',
            field=models.CharField(max_length=10),
        ),
    ]
